### PR TITLE
Terminate workers to avoid plugin counter errors

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes https://github.com/napari/napari-plugin-manager/issues/81

### CODE REVIEW

**Review by dalthviz — COMMENTED** [review]
Gave this a check and I'm still able to replicate the counter error:

plugins_counter

**Comment by goanpeca** [comment]
Will add a delay 👍🏼

**Comment by goanpeca** [comment]
@dalthviz added a timer to enable/disable the button after pressed. Could you check if this improves the situation?

Thanks!

**Comment by dalthviz** [comment]
Gave this another check and seems like the timer helped. Maybe it could be worthy to add some comment about the timer need and the issue it solved while explaining a little bit more why the counter errors where happening (for traceability)? Other than that this LGTM :+1:

**Comment by goanpeca** [comment]
>Gave this another check and seems like the timer helped. Maybe it could be worthy to add some comment about the timer need and the issue it solved while explaining a little bit more why the counter errors where happening (for traceability)? Other than that this LGTM 👍

Absolutely, will do!

Even without the timer it was much better, before the count was going to 800, 1000, 😆

**Review by dalthviz — APPROVED** [review]

**Pull request merged**
