### PR TITLE
Pin numpy <2 when installing plugins

### PR DESCRIPTION
**Pull request by Czaki**
following https://github.com/napari/napari/pull/6073

Ref: https://mail.python.org/archives/list/numpy-discussion@python.org/thread/RKH33EC5FTZOEBPX3GZSM2RKF4SDRGOW/

### CODE REVIEW

**Review by jaimergp — APPROVED** [review]
I am not sure how this will play out in future versions of `napari` but the change itself LGTM.

**Comment by jni** [comment]
I feel the same way as @jaimergp. I'm not 100% sure that we want this, especially for a project that doesn't use NumPy directly?

**Comment by jaimergp** [comment]
My main concern is that I feel these constraints (needed or not) should not be hardcoded in the source code, but specified in a configuration file that gets appended to the return value of that method. We _need_ a method to return the current napari version dynamically so we avoid an accidental down/up-grade, although this can be achieved with templating in a hypothetical configuration file too.

Then, this configuration can be adjusted on a as-needed basis, or with a data-only package that imposes restraints (e.g. `napari-pinnings` with calversioning).

I know PyPI doesn't have such a mechanism, but if napari doesn't depend on `numpy` directly, it should be on the packages that _do_ to patch their repodata or issue new releases covering that problem. If we start hardcoding every incompatibility in source code, if will get unmanageable pretty soon.

This kind or PR is ok for an urgent hotfix, if anything, but nothing else.

**Comment by Czaki** [comment]
@jni This is pin for installing plugins using plugin manager. Not plugin manager dependency itself. 
More advanced user could workaround this problem using console/terminal. 
Less advanced user will not break his environment unintentionally. 

Even when we as a project, do not use deprecated features it is possible that part of plugins do this (maybe indirectly using some libraries). 

I think that if we release 0.5.0 before numpy 2 then we should keep pin. And relax it in the next release after numpy 2.0 if we do not meet some problems.

**Comment by jni** [comment]
Thanks for the clarification @Czaki. That makes sense to me. @jaimergp do you agree with @Czaki's reasoning?

**Pull request merged**
