### PR TITLE
Initial napari specific classes for package installer related logic

### PR DESCRIPTION
**Pull request by dalthviz**
Part of #59

### CODE REVIEW

**Review by jaimergp — APPROVED** [review]

**Comment by jaimergp** [comment]
LGTM but let's have @goanpeca take a look too before the merge.

**Review by goanpeca — APPROVED** [review]
Hi @dalthviz just went thorugh the PR. Looks really good :) 

Thanks for wroking on this

**Comment by dalthviz** [comment]
> Is there anything that can be tested from the base implementations as to have separate test files also?
> 
> test_base_qt_installer...
> test_qt_installer...
> 
> ?

Thinking about that maybe we could move https://github.com/napari/napari-plugin-manager/blob/84f79a081077670d7b75bd4470a11bf439ec98f8/napari_plugin_manager/_tests/test_installer_process.py#L58-L70

to a `test_base_qt_installer`. Will do that change :+1:

**Comment by jaimergp** [comment]
Looks like we have a reproducible error in the Windows CI 🤔

**Comment by dalthviz** [comment]
I think I was able to fix it by adding a `qtbot.wait` but let me know if something else is needed here!

**Comment by dalthviz** [comment]
Should we merge this now and proceed with releasing v0.1.4 @jaimergp @goanpeca ? Or something else is missing?

**Comment by goanpeca** [comment]
I have a couple of PRs that I will merge afterwards, but I can also make a new minor release anyway :) 

So either way works for me

**Comment by dalthviz** [comment]
Oh I see, I think I will merge then this in an hour or so (if no other comment is added). Also, maybe we should list those other pending PRs over https://github.com/napari/napari-plugin-manager/issues/122 ? 🤔

**Comment by goanpeca** [comment]
Will work on those PRs today and will ping you back :)

**Pull request merged**
