### PR TITLE
Don't use `StringEnum` subclasses over Qt Signal definition

### LINKED ISSUE #94: Failing test with Pyside
The https://github.com/napari/napari/pull/7138 PR shows crashes of the test related to plugin manager when using PySide backend. 

I have skipped these tests, but it will be really nice to enable them again shortly.   

Problematic tests are `test_plugin_manager_action` and `test_import_plugin_manager` from `napari/_qt/_qapp_model/_tests/test_plugins_menu.py`

### LINKED ISSUE #103: Napari 0.5.3 installed from bundle file is interupted when installing plugins on UI
### 🐛 Bug Report

I installed Napari 0.5.3 from Bundle file. When I opened Napari &#8594; clicked <kbd>Plugins</kbd> &#8594; <kbd>Install/Uninstall Plugins ...</kbd>, the app closed immediately without any error messages.

### 💡 Steps to Reproduce

1. Download installation file here: https://github.com/napari/napari/releases/tag/v0.5.3
2. Install following this instruction: https://napari.org/stable/tutorials/fundamentals/installation_bundle_conda.html#how-to-install-the-linux-bundle
3. Open Napari
4. <kbd>Plugins</kbd> &#8594; <kbd>Install/Uninstall Plugins ...</kbd>

### 💡 Expected Behavior

_No response_

### 🌎 Environment

napari: 0.5.3
Platform: Ubuntu 22.04.3 - kernel: 6.8.0-40-generic
Python: 3.9.19

### 💡 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dalthviz**
Closes #94
Closes #103

### CODE REVIEW

**Review by jaimergp — APPROVED** [review]

**Comment by jaimergp** [comment]
LGTM, but is there a way we can test this breakage? We didn't catch this bad crash before.

**Comment by dalthviz** [comment]
The thing that was causing the tests to not fail was that the validation that skipped the whole `test_qt_plugin_dialog` module was skipping it if we where testing with PySide2 always (due to an `or` instead of an `and` in the validation). The related change to prevent that is at: https://github.com/napari/napari-plugin-manager/pull/104/files#diff-7974331479a4c742a92ad157da87de3e8f3b2a5ec09707b208b4ca377c2bd6caL17-R17

With the change done, now the module gets skipped only when actually is necessary (when using Python >3.10 and PySide2). This skip is needed since there are no wheels for PySide2 5.15 for Python >3.10. Trying to install PySide2 causes PySide2 5.13 to be installed with Python >=3.11 and that comes with some issues.

I also checked that reverting the `Signal` change, while keeping the change for the validation to apply the skip, causes the tests (`test_qt_plugin_dialog`) to fail:

* Without the `Signal` definition change but having the validation change on Windows with Python 3.10:

imagen

* With the `Signal` definition change and also the validation change on Windows with Python 3.10:

imagen
imagen

**Comment by psobolewskiPhD** [comment]
Amazing sleuthing as always @dalthviz 
❤️

**Comment by jaimergp** [comment]
Ok, thank you so much for the detailed explanation. Always a pleasure, let's merge this one.

**Pull request merged**
